### ISSUE TITLE
上传报错，需要滑动验证码

### ISSUE THREAD

**Issue by gifyic** [Aruelius/wenshushu#9]
当前已用空间:0.0GB,剩余空间:5.0GB,总空间:5.0GB                Traceback (most recent call last):                              File "wss.py", line 401, in <module>                            upload(file)                                                File "wss.py", line 389, in upload                              upload_main()                                               File "wss.py", line 362, in upload_main                         fname, tid, boxid, preid, upId = fast()
  File "wss.py", line 288, in fast
    boxid, preid, taskid, upId = addsend()
  File "wss.py", line 237, in addsend
    assert data, "需要滑动验证码"
AssertionError: 需要滑动验证码
不过我尝试在手机上在使用termux可以正常上传

**Comment by xtc-feedback** [comment]
可以想办法webview让用户来完成滑动验证码
